name: Upload iOS App to App Store

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 合并文件片段
    - name: Merge IPA parts
      run: |
        cat uploadtest/bango.ipa.part* > uploadtest/bango.ipa

    # 验证文件完整性
    - name: Verify file integrity
      run: |
        EXPECTED_MD5="f39c1508a6403ef3bcc379a70d01cd24"
        ACTUAL_MD5=$(md5 -q uploadtest/bango.ipa)
        
        if [ "$EXPECTED_MD5" != "$ACTUAL_MD5" ]; then
          echo "IPA file integrity check failed"
          exit 1
        fi

    # 上传到 App Store
    - name: Upload to App Store using altool
      env:
        IPA_PATH: "uploadtest/bango.ipa"
        APPLE_ID: "lemotree2025@outlook.com"
        APP_SPECIFIC_PASSWORD: "nwsh-bxkr-aqef-qtjl"
      run: |
        xcrun altool --upload-app -f "$IPA_PATH" \
          -t ios \
          -u "$APPLE_ID" \
          -p "$APP_SPECIFIC_PASSWORD" \
          --verbose

